### ISSUE TITLE
what ports need to be opened for indexer to work?

### ISSUE THREAD

**Issue by ralyodio** [ralyodio/dht_indexer#13]
It only crawls the 3 from the csv. nothing more is indexed.

**Comment by ralyodio** [comment]
>>> Number of new hashes fund in the last 15 minutes: 0

**Comment by 0xf333** [comment]
@ralyodio 
> Number of new hashes fund in the last 15 minutes: 0

https://github.com/ralyodio/dht_indexer/pull/4#issuecomment-1938732191
![Screenshot from 2024-02-23 08-55-45](https://github.com/ralyodio/dht_indexer/assets/100840345/ae842f44-5bf4-4025-bf6c-58bf808be9d0)

**Comment by ralyodio** [comment]
so do i need to open any ports?

**Comment by 0xf333** [comment]
@ralyodio 
> so do i need to open any ports?

No, you don't have to change anything. The current set up inside `Settings.toml` already handling it.
Secondly please read ticket #14
