### ISSUE TITLE
Let maintain repo stability

### ISSUE THREAD

**Issue by 0xf333** [ralyodio/dht_indexer#14]
## Description
Package upgrades sometimes come with changes that could potentially break their implementation in the repo, due to factors such as alterations in some internal functions. 

## Proposal:
Package upgrades should be initially restricted to a separate branch to allow for changes to be tested in isolation to preserve the integrity of the main branch. Reason being, If issues emerge during testing, these can be addressed and resolved prior to merging, to maintain stability/reliability. 
We should avoid tampering with the main branch. The current method of merging **will cause issues in the long run.**

## Request:
- Commit [ecfd929](https://github.com/ralyodio/dht_indexer/commit/ecfd929cb835bbbeb3609bbac24fcfe48f858539) should ideally be reverted.
- A staging branch should be created where initial packages updates will be introduced and tested/reviewed before merging.

## Impact:
Repository maintenance best practice to maintain stability/reliability.

**Comment by ralyodio** [comment]
overkill for this. i'm the only one who uses it and tests it.
