### ISSUE TITLE
Follow up and project maintenance 

### ISSUE THREAD

**Issue by 0xf333** [ralyodio/dht_indexer#5]
Hi @ralyodio 
Just following up on this repo for project maintenance. 

## Please Run This Test
1. Make sure that you have the latest commit of the repo.
2. Run it on a different server to avoid any confusion with any other versions of this CLI app that you might be running at the moment.
3. Without making any changes or edits, and without replacing the `.db` file with an old one, let this isolated test run from scratch.

### Let It Run For 24 Hours
- After the specified time, please create new GitHub tickets for any adjustments needed and I will proceed to work on these. 

## Please Note
- Keep each ticket specific to one thing regarding the CLI app. Instead of encompassing everything in one ticket, please maintain separation for easier tracking and resolving.

**Comment by ralyodio** [comment]
well my isp blacklisted me because of mpaa honey pots. i need a freespeach hosting platform.

**Comment by 0xf333** [comment]
> well my isp blacklisted me because of mpaa honey pots. i need a freespeach hosting platform.

You didn't use the Proton CLI vpn as suggested?

**Comment by ralyodio** [comment]
nordvpn doesn't work that way. i got a vps in sweden. so we'll see how that goes.

**Comment by 0xf333** [comment]
@ralyodio 

>nordvpn doesn't work that way. i got a vps in sweden. so we'll see how that goes.

You need a CLI vpn so you can run it inside the VPS. Proton vpn has one.

**Comment by ralyodio** [comment]
i don't think it'll work. have you tried?

**Comment by 0xf333** [comment]
@ralyodio 

> i don't think it'll work. have you tried?

https://protonvpn.com/support/linux-vpn-tool/#debian

**Comment by ralyodio** [comment]
does this work with the free vpn?
