### ISSUE TITLE
Restrict the continuous tracking of indexed hashes

### ISSUE THREAD

**Issue by 0xf333** [ralyodio/dht_indexer#8]
## Description

After the initial indexing, indexed hashes are periodically updated indefinitely. While this is acceptable initially, we need to consider scenarios where the indexer has thousands of hashes to track. This continuous tracking could strain system resources, particularly on low-spec servers.

<br>

## Proposal
To maintain the indexer's efficiency and keep it low-spec servers friendly, I would suggest limiting the tracking of indexed hashes with the following:

- **Limiting Tracking Sessions**: 
    - An implementation of a limit of 5 sessions per indexed hash to free up the tracking module for future batches so the tracking process doesn't overload the system with excessive updates.

- **Modifying Tracking Module Behavior**: 
    - Instead of initializing seeder/leecher counts as zero during the first indexing and then updating them in subsequent tracking sessions, I would suggest that we modify the tracking module to log seeder/leecher counts directly from the initial capture, as it will be better to streamline the tracking process and reduces the need for multiple updates! 

<br>

## Impact
These will optimize the tracking process while making sure that the system remains scalable but yet resource-efficient, especially under heavy load conditions.

**Comment by ralyodio** [comment]
ideally the web interface would have a "refresh" button that manually triggers an update.

**Comment by 0xf333** [comment]
> ideally the web interface would have a "refresh" button that manually triggers an update.

I see... 
The frontend dev can use the exposed `trackTorrent` in my next PR then ( #11 )

**Comment by 0xf333** [comment]
Ticket closed by PR number  #11
